# Get your client id and secret
# https://developer.spotify.com/documentation/general/guides/authorization/app-settings/
#
# This client id and secret can't be used. You have to use your own client id and secret

client-id: "3cb0806ca65f4198af37788e9ff22e03" # Your client ID
client-secret: "a77d5fc361d140a184de94cc0ed69d67" # Your client secret